services:
  frontend:
    build: 
      context: ./www
      args:
        NEXT_PUBLIC_API_BASE_URL: http://web-app:5000
    ports:
      - 3000:3000
    develop:
      watch:
        - action: rebuild
          path: ./www
    depends_on:
      - web-app

  web-app:
    build: ./
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres-db:5432
      PORT: 5000
      ROCKET_ADDRESS: 0.0.0.0
    restart: always
    volumes:
      - tmp:/app/tmp
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:17.0
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  tmp:
