services:
  web-app:
    build: ./
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres-db:5432
      PORT: 5000
      ROCKET_ADDRESS: 0.0.0.0
    depends_on:
      - postgres-db
    volumes:
      - tmp:/app/tmp

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  tmp:
