
services:
  web-app:
    build: ./
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres-db:5432
      PORT: 8080
      ROCKET_ADDRESS: 0.0.0.0
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres_db"]
      interval: 30s
      timeout: 10s
      retries: 5
  